### ISSUE TITLE
errror in sub category

### ISSUE THREAD

**Issue by Manikandan88564** [romanejaquez/orilla_fresca_app#15]
i need to pass one more parameter in category page.....

heree is my code,,

import 'dart:ui';

class Category {
  String name;
  String image;
  String? productcount;
  List<Category>? subCategories;
 
  Category({
    required this.name,
    required this.image,
    this.productcount,
    this.subCategories,
  });
}

&& subcategory code

import 'dart:ui';

import 'category.dart';

class SubCategory extends Category {
  SubCategory({
    required String name,
    required String image,
    required int price,
    required String qty,
  }) : super(
          name: name,
          image: image,
          // productcount: productcount,
        );
}

i need to pass productcount

**Comment by Manikandan88564** [comment]
i need to print price and quatity print in selectedcategorypage..

**Comment by romanejaquez** [comment]
You would still have to provide the productCount via the SubCategory's constructor or provide a default parameter for it. 

Paste this in dartpad.dev so you can see:

```
void main() {
  
  SubCategory sub = SubCategory(
    name: 'Subname',
    image: 'imgName',
    price: 30,
    qty: '30'
  );
  
  print((sub as Category).productcount);
}

class Category {
String name;
String image;
String? productcount;
List? subCategories;

Category({
required this.name,
required this.image,
this.productcount,
this.subCategories,
});
}

class SubCategory extends Category {
SubCategory({
required String name,
required String image,
required int price,
required String qty,
String productCount = 'somecount'
}) : super(
name: name,
image: image,
productcount: productCount,
);
}

```

Then go back up to the SubCategory sub and add a productCount in the constructor as such:

```
SubCategory sub = SubCategory(
    name: 'Subname',
    image: 'imgName',
    price: 30,
    qty: '30',
    productCount: '3'
  );
```

Re-run and see how when you print:
```
(sub as Category).productcount
```
you should see the value of '3'.

Other recommendations:
-try making your variables camel case (productCount)
-try making variables that involve count as integers
-anything that has to do with price as double (you currently have price as int, should make it as double if possible)
-productCount you currently have it as a String (unless strictly necessary, otherwise I'd make it an integer)

Let me know if those changes work for you

**Comment by Manikandan88564** [comment]
i need to print price and quantity print in selectedcategorypage..


![demo db](https://user-images.githubusercontent.com/59675702/145942227-cd812be9-4935-4511-9fb8-7075463f5ae7.png)

**Comment by Manikandan88564** [comment]
![image](https://user-images.githubusercontent.com/59675702/145943249-3ea0eb6e-af3d-4084-b27c-db0090b3a133.png)

i tried your code its given o/p in dart.dev but it showing error in selectedcategory page...

**Comment by romanejaquez** [comment]
I see you're assigning productcount to category. Do you mind sending me your code so I can help you figure out the issue? You can send me your repo and I'll clone it locally to take a look. Thanks!

**Comment by Manikandan88564** [comment]
https://drive.google.com/file/d/1adKXlvq6GBPOl_XobE2I31Rt3SPrl6dn/view?usp=sharing

**Comment by Manikandan88564** [comment]
https://drive.google.com/file/d/16pWCzymoiO8c9KswUBYfziIAmypKLXmP/view?usp=sharing

**Comment by romanejaquez** [comment]
Hey @Manikandan88564 check out in the code below how I did it (attached as a Google Drive link). I'm able to pass the selected subcategory as well as consume the product count down on the details page. Since the SubCategory inherits from Category, you can easily consume the productcount from there, all you need to make sure is that the value is properly set. Let me know if that helps!
https://drive.google.com/file/d/1Iv-id4D-R5ICDwagbXS_eOjuE34Ogv5-/view?usp=sharing

**Comment by Manikandan88564** [comment]
yes.. it works... thanks :)
