### ISSUE TITLE
i need your help 

### ISSUE THREAD

**Issue by kurd-dev** [romanejaquez/orilla_fresca_app#9]
hello dear 
as i saw your video it was very clear and  attractive thanks 
but would you help me to finish my project im stack in the end of project if you help me i will be glad 

[https://www.dropbox.com/s/cyytm9tmj81zfvo/detailspage.dart?dl=0](https://www.dropbox.com/s/cyytm9tmj81zfvo/detailspage.dart?dl=0)

this is my **detailspage** class , i take it away the some parts of code that you implemented  i putted my own code to display a image and text information , it works well but one problem surfme ,i need my screen will be scrollable but **my screen has an issue , it can't be scrollable**   i cant move up and down, i implement many of the scrollable widget  but it wasn't work for me  , could you help me to make scrollable?????

best regard

**Comment by romanejaquez** [comment]
hi @kurd-dev did you try wrapping the content of your screen inside a SingleChildScrollView, but setting a height to its immediate child? (https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html)

Your issue is that you cannot provide unbound limits (heightwise) to your main container, otherwise you'll have to use a ListView or something, and append a bunch of widgets inside of it of different kinds. The SingleChildScrollView will scroll through the contents of its child, so long it has a pre-determined height to it. You will have to set a height to the main Container (perhaps a calculation of the height of every child inside. Check out the gist below (running on DartPad). I set the height of the main Container to be (as an example) twice the height of the screen using the MediaQuery widget.

I believe this is what you want to do; use the scrollwheel and see how I made the whole content scroll.
https://gist.github.com/romanejaquez/1ed5093d7d2a868b9fbdb07049153f7b#file-scrollable-content-flutter-dart

Let me know if you have any other issues.

**Comment by kurd-dev** [comment]
Emm it actually worked but the screen size  a bit mess when scrolling down , the appbar will disappear and the bottom of the screen is very annoying for the user because the half of the screen is empty . It doesn't stick according of the text .
https://user-images.githubusercontent.com/62264816/131142311-c6df4d4d-c1d1-4342-856d-7c1fbb9770f4.MOV

**Comment by kurd-dev** [comment]
Will u answer me ?

**Comment by romanejaquez** [comment]
hey @kurd-dev sorry - busy at work. My suggestion to you is not make the whole page scrollable. Make only a portion of the page scrollable. The appbar should remain sticky to the top. Make only a Container inside the page scrollable, not the whole page. If you see the way I did it on the application, i made only the second half of the screen scrollable. That is my suggestion to you.

**Comment by kurd-dev** [comment]
thanks alot i fixed by my own way thanks alot right now the screen size will stick with the text. thanks alot
